# Generated by Django 4.0.2 on 2022-03-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=99)),
                ('Description', models.CharField(max_length=10000000)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
