# Generated by Django 4.0.2 on 2022-03-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='Product_Name',
            new_name='Product',
        ),
    ]
