# Generated by Django 4.0.2 on 2022-03-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auctionlistings_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='buyer',
            new_name='seller',
        ),
    ]
