# Generated by Django 4.0.2 on 2022-03-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_buyer_auctionlistings_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
